<template>
  <div class="shell">
    <AdminSidebar />
    <main class="main"><header><div><span>管理控制台 / </span><b>电影管理</b></div><el-button circle plain title="刷新" :loading="loading" @click="load"><el-icon><Refresh /></el-icon></el-button></header>
      <section class="heading"><div><h1>电影管理</h1><p>搜索、查看并维护平台电影资料。</p></div><el-tag type="info" effect="plain">{{ total }} 部记录</el-tag></section>
      <el-card shadow="never" class="filter"><el-form inline @submit.prevent="load"><el-form-item label="关键词"><el-input v-model="filters.keyword" clearable placeholder="标题、导演或豆瓣 ID" @keyup.enter="load" /></el-form-item><el-form-item label="类型"><el-input v-model="filters.genre" clearable placeholder="如：剧情" /></el-form-item><el-form-item label="年份"><el-input-number v-model="filters.year" :min="1880" :max="2100" :controls="false" placeholder="年份" /></el-form-item><el-form-item label="状态"><el-select v-model="filters.status" style="width:120px"><el-option label="正常" value="ACTIVE" /><el-option label="回收状态" value="DELETED" /></el-select></el-form-item><el-button type="primary" @click="load"><el-icon><Search /></el-icon>查询</el-button><el-button @click="reset">重置</el-button></el-form></el-card>
      <el-card shadow="never" class="table-card"><el-table v-loading="loading" :data="movies" stripe><el-table-column label="电影" min-width="260"><template #default="{ row }"><div class="movie"><img v-if="row.posterUrl" :src="row.posterUrl" alt="" /><div><b>{{ row.title }}</b><small>{{ row.doubanId || '无豆瓣 ID' }}</small></div></div></template></el-table-column><el-table-column prop="genre" label="类型" min-width="150" show-overflow-tooltip /><el-table-column label="上映日期" width="120"><template #default="{ row }">{{ row.releaseDate || '--' }}</template></el-table-column><el-table-column label="评分" width="130"><template #default="{ row }">豆瓣 {{ row.doubanRating ?? '--' }}<small class="muted">用户 {{ row.avgRating ?? '--' }}</small></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'DELETED' ? 'danger' : 'success'" size="small">{{ row.status === 'DELETED' ? '回收' : '正常' }}</el-tag></template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button v-if="row.status !== 'DELETED'" link type="danger" @click="remove(row)">删除</el-button><el-button v-else link type="success" @click="restore(row)">恢复</el-button></template></el-table-column><template #empty><el-empty description="暂无电影记录" /></template></el-table><div class="pager"><el-pagination v-model:current-page="page" v-model:page-size="size" :total="total" :page-sizes="[10,20,50]" layout="total, sizes, prev, pager, next" @current-change="load" @size-change="changeSize" /></div></el-card>
    </main>
    <el-dialog v-model="dialog" title="编辑电影资料" width="680px"><el-form ref="formRef" :model="form" label-width="90px"><el-form-item label="片名" prop="title" required><el-input v-model="form.title" /></el-form-item><el-form-item label="导演"><el-input v-model="form.director" /></el-form-item><el-form-item label="主演"><el-input v-model="form.actors" type="textarea" :rows="2" /></el-form-item><el-form-item label="类型"><el-input v-model="form.genre" /></el-form-item><el-form-item label="上映日期"><el-date-picker v-model="form.releaseDate" type="date" value-format="YYYY-MM-DD" /></el-form-item><el-form-item label="片长"><el-input-number v-model="form.runtime" :min="1" /></el-form-item><el-form-item label="简介"><el-input v-model="form.summary" type="textarea" :rows="4" /></el-form-item><el-form-item label="海报 URL"><el-input v-model="form.posterUrl" /></el-form-item><el-form-item label="豆瓣评分"><el-input-number v-model="form.doubanRating" :min="0" :max="10" :precision="1" :step="0.1" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存修改</el-button></template></el-dialog>
  </div>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Refresh, Search } from '@element-plus/icons-vue'
import AdminSidebar from '../components/AdminSidebar.vue'
import { deleteAdminMovie, getAdminMovies, updateAdminMovie, type AdminMovie } from '../api/admin'
const movies = ref<AdminMovie[]>([]); const loading = ref(false); const saving = ref(false); const dialog = ref(false); const selectedId = ref<number>(); const page = ref(1); const size = ref(20); const total = ref(0)
const filters = reactive<{ keyword?: string; genre?: string; year?: number; status: string }>({ status: 'ACTIVE' }); const form = reactive<Partial<AdminMovie>>({})
async function load() { loading.value = true; try { const res: any = await getAdminMovies({ current: page.value, size: size.value, ...filters }); if (res.code !== 200) throw new Error(res.message); movies.value = res.data?.records || []; total.value = res.data?.total || 0 } catch (e: any) { ElMessage.error(e.message || '电影列表加载失败') } finally { loading.value = false } }
function reset() { filters.keyword = undefined; filters.genre = undefined; filters.year = undefined; filters.status = 'ACTIVE'; page.value = 1; load() }
function changeSize() { page.value = 1; load() }
function openEdit(row: AdminMovie) { selectedId.value = row.id; Object.assign(form, row); dialog.value = true }
async function save() { if (!selectedId.value || !form.title?.trim()) return ElMessage.warning('片名不能为空'); saving.value = true; try { const payload = { title: form.title, director: form.director, actors: form.actors, genre: form.genre, releaseDate: form.releaseDate, runtime: form.runtime, summary: form.summary, posterUrl: form.posterUrl, doubanRating: form.doubanRating }; const res: any = await updateAdminMovie(selectedId.value, payload); if (res.code !== 200) throw new Error(res.message); ElMessage.success('电影资料已更新'); dialog.value = false; await load() } catch (e: any) { ElMessage.error(e.message || '保存失败') } finally { saving.value = false } }
async function remove(row: AdminMovie) { await ElMessageBox.confirm(`确定将《${row.title}》移入回收状态吗？`, '二次确认', { type: 'warning', confirmButtonText: '确认删除', cancelButtonText: '取消' }); try { const res: any = await deleteAdminMovie(row.id); if (res.code !== 200) throw new Error(res.message); ElMessage.success('已移入回收状态'); await load() } catch (e: any) { if (e !== 'cancel') ElMessage.error(e.message || '删除失败') } }
async function restore(row: AdminMovie) { try { const res: any = await updateAdminMovie(row.id, { status: 'ACTIVE' }); if (res.code !== 200) throw new Error(res.message); ElMessage.success('电影已恢复'); await load() } catch (e: any) { ElMessage.error(e.message || '恢复失败') } }
onMounted(load)
</script>
<style scoped>
.shell{min-height:100vh;background:#f4f6f8;color:#263442}.side{position:fixed;inset:0 auto 0 0;width:220px;background:#fff;border-right:1px solid #e5e9ed;padding:24px 14px;display:flex;flex-direction:column}.brand{display:flex;gap:10px;align-items:center;padding:0 10px 30px;font-weight:700}.brand b{display:grid;place-items:center;width:36px;height:36px;border-radius:7px;background:#176b63;color:white;font-size:18px}.brand span,.brand small,.account span,.account small{display:block}.brand small,.account small{color:#97a1a9;font-size:11px;font-weight:400;margin-top:3px}nav{display:grid;gap:5px}nav a{padding:11px 12px;color:#68757e;text-decoration:none;border-radius:5px;font-size:13px}nav a.active,nav a:hover{background:#eaf4f2;color:#176b63;font-weight:600}.account{margin-top:auto;border-top:1px solid #edf0f2;padding-top:14px;display:flex;align-items:center;gap:8px;font-size:12px}.account span{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.main{margin-left:220px;padding:0 32px 40px;max-width:1500px}header{height:61px;border-bottom:1px solid #e5e9ed;display:flex;justify-content:space-between;align-items:center;font-size:12px}header span{color:#89949d}.heading{display:flex;justify-content:space-between;align-items:center;padding:26px 0 20px}.heading h1{margin:0;font-size:23px}.heading p{color:#89949d;font-size:12px;margin:7px 0 0}.filter,.table-card{border:1px solid #e5e9ec;margin-bottom:14px}.filter :deep(.el-card__body){padding:17px 18px 4px}.table-card :deep(.el-card__body){padding:0}.filter .el-form-item{margin-bottom:13px}.movie{display:flex;align-items:center;gap:10px}.movie img{width:34px;height:46px;object-fit:cover;border-radius:3px;background:#eef1f3}.movie b,.movie small{display:block}.movie b{font-size:13px}.movie small,.muted{font-size:11px;color:#9aa4ac;margin-top:4px}.pager{display:flex;justify-content:flex-end;padding:15px}.el-table{font-size:12px}
@media(max-width:900px){.side{width:180px}.main{margin-left:180px;padding:0 16px}.filter :deep(.el-form-item){margin-right:8px}.heading{padding-top:20px}}
</style>
