app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  refresh-cookie-secure: ${JWT_REFRESH_COOKIE_SECURE:true}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
